// Error
export const DISMISS_ERROR = 'DISMISS_ERROR';

// Auth
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// Create
export const CLIENT_CREATE_REQUEST = 'CLIENT_CREATE_REQUEST';
export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const CREATE_FAIL = 'CREATE_FAIL';

// Lists
export const CLIENT_LIST_REQUEST = 'CLIENT_LIST_REQUEST';
export const SUBSCRIPTION_LIST_REQUEST = 'SUBSCRIPTION_LIST_REQUEST';
export const PROVIDER_LIST_REQUEST = 'PROVIDER_LIST_REQUEST';
export const SERVICE_LIST_REQUEST = 'SERVICE_LIST_REQUEST';
export const PLAN_LIST_REQUEST = 'PLAN_LIST_REQUEST';
export const LIST_SUCCESS = 'LIST_SUCCESS';
export const LIST_FAIL = 'LIST_FAIL';

// Detail
export const CLIENT_DETAIL_REQUEST = 'CLIENT_DETAIL_REQUEST';
export const SUBSCRIPTION_DETAIL_REQUEST = 'SUBSCRIPTION_DETAIL_REQUEST';
export const DETAIL_FAIL = 'DETAIL_FAIL';
export const DETAIL_SUCCESS = 'DETAIL_SUCCESS';
